#!/usr/bin/env sh

# Loadscript
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_border on \
	config external_bar "all:34:0" \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_zoom_persist off \
	window_placement second_child \
	window_topmost off \
	window_shadow float \
	window_opacity on \
	window_opacity_duration 0.15 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.95 \
	window_border_width 4 \
	window_border_hidpi on \
	window_border_radius 0 \
	window_animation_duration 0.22 \
	active_window_border_color 0xffe1e3e4 \
	normal_window_border_color 0xff2a2f38 \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_drop_action swap \
	mouse_action2 resize \
	\
	top_padding 10 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 8

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m config layout bsp

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^KakaoTalk$" manage=off
yabai -m rule --add app="^Finder$" manage=off
