-- return {
--   "iurimateus/luasnip-latex-snippets.nvim",
--   -- vimtex isn't required if using treesitter
--   requires = { "L3MON4D3/LuaSnip" },
--   config = function()
--     require("luasnip-latex-snippets").setup()
--     -- or setup({ use_treesitter = true })
--     require("luasnip").config.setup({
--       enable_autosnippets = true,
--       use_treesitter = true, -- whether to use treesitter to determine if cursor is in math mode; if false, vimtex is used
--       allow_on_markdown = false, -- whether to add snippets to markdown filetype
--     })
--   end,
-- }
